openapi: "3.0.2"
info:
  title: ABH VPS Trace route
  description: |-
    Sebuah poratl untuk memembeli sebuah VPS. VPS yang digunakan
    diaharakanakan digunakan untuk melakukan treace route pada
    list ip adrress yang telah disediakan 
  version: "1.0"
servers:
  - url: https://localhost:3000/v1

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        company:
          type: string
        occupation:
          type: string
        phone:
          type: string
    Server:
      type: object
      properties:
        id:
          type: string
        ownner:
          $ref: "#/components/schemas/User"
        name:
          type: string
        vcpu:
          type: integer
        ram:
          type: integer
        storage:
          type: integer
        selinux:
          type: boolean
        firewall:
          type: boolean
        ipv4address:
          type: string
        username:
          type: string
        password:
          type: string
        powerStatus:
          type: boolean
        timeLimit:
          type: string
        created_at:
          format: date-time
        updated_at:
          format: date-time
        deleted_at:
          format: date-time
  securitySchemes:
    ownerAuthor:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://domain.test/api/oauth/dialog
          tokenUrl: https://domain.test/api/oauth/token
          scopes:
            read:user: read user data
            write:user: write user data
paths:
  /signup:
    post:
      tags:
        - User
      summary: register user
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
    get:
      tags:
        - Frontend
      summary: register user
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
  /signin:
    get:
      tags:
        - Frontend
      description: ""
      summary: login user
      parameters: []
      responses:
        "200":
          description: OK
    post:
      description: ""
      summary: user login
      tags:
        - User
      parameters: []
      responses:
        "200":
          description: OK
  /:
    get:
      tags:
        - Frontend
      summary: landing page home dari web portal
      description: dalam dashboard user dapat mencari Server yang di temui
      parameters: []
      responses:
        "200":
          description: OK
  /user/settings:
    get:
      description: user see their data settings registered in our database
      tags:
        - Frontend
      summary: get user details
      parameters: []
      security:
        - ownerAuthor:
          - read:user
      responses:
        '200':
          description: OK
    put:
      summary: update user settings
      tags:
        - User
      description: ''
      parameters: []
      security:
        - ownerAuthor:
          - write:user
      responses:
        '200':
          description: OK
  /ServerList:
    get:
      description: ''
      tags:
        - ServerList
      parameters: []
      security:
        - ownerAuthor:
          - read:user
      responses:
        '200':
          description: OK
    post:
      description: ''
      parameters: []
      tags:
        - ServerList
      security:
        - ownerAuthor:
          - read:user
      responses:
        '200':
          description: OK
  /ServerList/{id_server}:
    get:
      description: ''
      parameters: []
      tags:
        - ServerList
      security:
        - ownerAuthor:
          - read:user
      responses:
        '200':
          description: OK
    put:
      description: ''
      parameters: []
      tags:
        - ServerList
      security:
        - ownerAuthor:
          - read:user
      responses:
        '200':
          description: OK
    delete:
      description: ''
      parameters: []
      tags:
        - ServerList
      security:
        - ownerAuthor:
          - read:user
      responses:
        '200':
          description: OK
    


